### ISSUE TITLE
Beliefs not being updated

### ISSUE THREAD

**Issue by pedrodbs** [usc-psychsim/psychsim#11]
When setting a belief to an agent, the belief is not updated as a consequence of actions that change the corresponding feature.

E.g., in the `imperfect_action_model.py` example in the `small-examples` branch, the agent has an incorrect belief over its position, but its actions (eg move right) should change that belief accordingly, which does not occur.
 
During forward planning the beliefs *are* updated but then they are disregarded in line 182 of `world.py`:
```python
agentsModeled = [name for name in self.agents
                                 if modelKey(name) in state.keyMap and self.agents[name].omega is not True]
```

results in an empty list because the agent's default `omega` is `True`.

EDIT: Setting `agent.omega = {actionKey(agent.name)}` does work but it doesn't seem to be what we want right?

Is there a built-in way to automatically update the agent's beliefs?

**Comment by pynadath** [comment]
It's not automated, because honestly, people should be very explicit about what's being observed and what's not. But we could set omega to be just actionKey(agent.name) when first setting imperfect beliefs, because there's an inconsistency if omega stays as True in this case. And if omega is empty, then the agent does not observe even its own action, and it has no basis of updating its beliefs based on its own actions.

**Comment by pedrodbs** [comment]
oh ok, but from the user perspective that should be more clear (I found the solution by trial-and-error). Maybe having the action as default in omega after `agent.setBelief()` is better.

Also, adding an agent's variable in omega generates an error (impossible observation?), which is not very intuitive.
