### ISSUE TITLE
Cannot have access to agents' decisions

### ISSUE THREAD

**Issue by pedrodbs** [usc-psychsim/psychsim#2]
It seems world.step() function no longer stores the agents' decisions information on the 'outcomes' variable. 
How can one work with world.explain() and other custom explainability functions?

**Comment by pynadath** [comment]
step no longer returns all that information because it can be costly to package it up as the number of agents grows. What I'd like to do (well, what I'd like someone else to do) is to use the "debug" argument to be a structure that accumulates whatever explanation information is desired. For example, "debug" could be a dictionary with empty entries for some subset of agent names, and the decision structures for only those agents gets put into the dictionary.

**Comment by pedrodbs** [comment]
Hum I see the 'debug' argument, but is that being used in any way or are you saying we should populate it during decide()/step(), etc?
Could a solution be to store the 'outcomes' dict if debug contains 'True' or something?
